language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "pypy"
  - "pypy3"
# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: true

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install pip --upgrade
    - pip install pytest>=2.7.3 --upgrade

# command to run tests, e.g. python setup.py test
script:
    - python setup.py sdist --format=zip
    - pip install dist/dominate*.zip
    - py.test

after_success:
    - pip install coveralls coverage
    - PYTHONPATH=. coverage run --source=dominate -m pytest
    - coverage report
    - coveralls

sudo: false
